### ISSUE TITLE
Stick Anything Offset Setting won't function

### ISSUE THREAD

**Issue by GamingGav** [oceanwp/ocean-stick-anything#1]
The Stick Anything extension offset setting won't function. No matter what number I put in, the stick comes once the element hits the top of the page with no spacing happening.
![stickyanythingbug01](https://user-images.githubusercontent.com/55333871/103940047-c578b380-50fa-11eb-94e2-2e224ffd23b9.jpg)
![stickyanythingbug02](https://user-images.githubusercontent.com/55333871/103940081-d0334880-50fa-11eb-92b2-bff478ecc037.jpg)
![stickyanythingbug03](https://user-images.githubusercontent.com/55333871/103940088-d32e3900-50fa-11eb-9402-ff53b5b303d8.jpg)

**Comment by eramits** [comment]
Hello,

Sorry for the late reply. Do you still have this issue? If yes, can share the page URL. For now, I'm closing this issue. You can always open a new one.

**Comment by eramits** [comment]
Issue fixed - 

[Offset Setting does not function](https://github.com/oceanwp/ocean-stick-anything/pull/3)
